name: Build Oracle Connector

on:
  push:
    paths:
      - 'pom.xml'
      - 'debezium-connector-oracle/**'
  pull_request:
    paths:
      - 'pom.xml'
      - 'debezium-connector-oracle/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
#      - name: Setup Debezium Parent
#        run: git clone https://github.com/debezium/debezium.git $PWD/core-repo && cd $PWD/core-repo && mvn -B clean install -DskipTests -DskipITs -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn && cd $OLDPWD
      - name: XStream JAR SetUp
        run: mvn install:install-file -DgroupId=com.oracle.instantclient -DartifactId=xstreams -Dversion=12.2.0.1 -Dpackaging=jar -Dfile=xstreams.jar
      - name: Check changes in Debezium Connector Oracle
        run: mvn clean install -DskipITs=true -pl debezium-connector-oracle -am -Poracle -Dinstantclient.dir=/path/to/instant-client-dir
